apiVersion: v1
kind: Secret
metadata:
    name: michael-secrets
    namespace: denny-agents
type: Opaque
stringData:
    DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:G2BTPIHOk6wdnSESy7L/uC6I5ALbI8UhfMrbzkKjEITSgIpinzb+lpVyBEgl7jEaUd3mh3I847DDyu+9apknE9FudF82zXXD,iv:X91pMGQlQ1xKrhIiELYYoUySE4m8BZpdYVlT8aKC/Qc=,tag:jmcojlkjT7Bd/QiTdEWVcg==,type:str]
    ANTHROPIC_OAUTH_TOKEN: ENC[AES256_GCM,data:kaZ7qt2qSQIkgF8advGdcQq/l3a+zaDmSHJBlgoSJXVVN+RaFOYqGQtVHbw1nwfXbH8A5IG7vb/6tS4lQbL7C95w/aQE6uxF5QBAfb0uLdKtsgN3Ah7kyTxjEhpezrqycdnhCDj1w3po3gHt,iv:PBlfyAjCvkHh/U/ETYgJvLLe6K4paDkBd8u2Ct4EoTs=,tag:J50mmhQ6lyO54yF+LSWzpA==,type:str]
    GH_TOKEN: ENC[AES256_GCM,data:7aBvjpGThA1b8JisYSG4s8YfufCWUsS+rKJbDI0weG5wBUro07w1Ng==,iv:kMDYBzNJ99T8Tql0HHWHE2cgu/wiArhFo1QDzpEGtL8=,tag:xk/vwfHkT+fEG+lMfyz0lA==,type:str]
    JIRA_API_TOKEN: ENC[AES256_GCM,data:4MtydAVZUA0S0cmxaYUYjrKo/KeMBt9UONO2eZpI+23ljVdbxGxAE/z5o68MUSxPOe24hweSNhyrpYYpalINlw7SXWGrEOGwy3vuQ95/VQO6bMVqqHd3jwIONuMcViU2gYeg3qnboOa+I5R3tkmXBHzUrjT+y2KpZtowq017gUHJq/qLiKazpwKVFOk2xTlGgAb+fZxJq5BfekHXpnmM44sYSccDzGQXUepptRJg8aF4TpfmvzcJt/KDne/d76RW,iv:xgkP3qiaKuk44KdNol9Yd0LJ0rB8ExmL7aZnXYJorTY=,tag:IV2Hr8QDP/K5u/3q+mKuJw==,type:str]
sops:
    age:
        - recipient: age1xa2x5q6zpcrwjq9xyh9ghmm57mvzu5d0e0yehtqujdjfyjxpe9rqu60den
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBINVRMUlp5a09JdTFjM2tO
            WnQzMlBib2JNcUhNTnoxaEhYZGVZa3VreGxJCk5kRlloQjVKVVZvVVZvdWFTV3Av
            T3lMSmZVRlBUYW96T1M3QkFtNzZrd00KLS0tIDhzTmM3R01aUTgzYjhiZkUzeEtH
            dFNPT2Nnbno3SnJzakRlemZleEpaOHMKoHGuzvPTiGTZcu1liO4n/o2YtnGK1Ixl
            C+YD0yLvl77dhRzPf5L8zxEXLKzSErVrIuJQWVX3C9SWSupOyQS9wg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-23T13:41:02Z"
    mac: ENC[AES256_GCM,data:+TEOcTHElaVLSc/xDq26CMqytrO6b+XVoP9Amdf5Ilw5dY4HACJtkP5vdp1vh5P3ESGD2nx51HYZjj1cu5v+T9D5VCp63VpV3w0+ZhEZ3V42NT7/W75FtHgJ+SZL4GgmyTy3Ln/EH7FolfCDQG5mHz3G2rU3qzXi0EZO+6AuDV0=,iv:SKOng2UO12SVIoaUTzfFI4AhN1eA4zH5aKKPGOHn/PQ=,tag:aGDLBPU1NNyuV/xrzE7zIQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
