apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tom-home
  namespace: denny-agents
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: tom-home
  resources:
    requests:
      storage: 10Gi
