apiVersion: v1
kind: Secret
metadata:
    name: todo-db-credentials
    namespace: todo-app
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:zCij8IrMeg==,iv:2LbCkqHu0PJm168kvFkitaEqpHLrfwroz3TBg1JAFjw=,tag:lpVuHGF83b4kW509jlQWlw==,type:str]
    password: ENC[AES256_GCM,data:ZaZQfAZrzbDq/Qk9VZ+LmvfKBg==,iv:MeTBczy/3PTS5cg37vhvuIijTNh3QosGGnZCMkS4gl0=,tag:WJHepYRtjuN+Lu6SjBrVxQ==,type:str]
    url: ENC[AES256_GCM,data:qTWxepnnzsCHqWcvt6MIWItpxIp1RBfSQUEhUekPwrKXvV5TqgBzYBTtrsVIcCVDJRkQhsQJQ3bSguIOpko=,iv:HwgGxsydZCgI/sJfmyJl+KkhtXosCFpacsgADh0jyWc=,tag:zQVaw1SBemF3u7nZ3dt/FA==,type:str]
sops:
    age:
        - recipient: age1xa2x5q6zpcrwjq9xyh9ghmm57mvzu5d0e0yehtqujdjfyjxpe9rqu60den
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3cUpWa0I2U0tXMWJWdkNL
            WDQ3WEQ4R2xBVGNrOGZFVThMV0tIQjFEOEZ3Ck5xRmh1UllsbEFqVmRad2t0OGlv
            QThzdmUwaFZ2akxNRFNLT1N3Ymd2MjQKLS0tIEoydkdBemJyUGVvMVJDQ3RNM2NV
            L29aM3pGMmtKTVpvbU5PeTVNRmhRMFEK1hGP222IpL7QXJ9xefzqCZuzqozFo6Td
            CcJRtVRqeD5ua5O5YjuNOm6wRyD33AEiR8Aqcvi3+XLft17Zo+Y6Iw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-23T14:27:17Z"
    mac: ENC[AES256_GCM,data:YirhTn7SP+UnO4Xs8oo5DJ8AQfPM3F2IznaYcOOz1TuxuolnYcPY2ZgnQKMTGZOViRQ6eV0zwXuGfun6l2Nife7msKW2diGCMtByBNugzvOxmBIodvz4U1csbaXf5stQAKyPhEwDUtkhyZqTD5o0LaNDGus9uAs+iD4i7Pl7fAM=,iv:mBvwNhiNBf2ZLwxzyQyQW18QI55sO/MDPaJQROonix0=,tag:VTC9gEwEq6vf4z02YE6SUw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
