apiVersion: v1
kind: PersistentVolume
metadata:
  name: tom-home
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /opt/denny/agent-data/tom
    type: Directory
  claimRef:
    namespace: denny-agents
    name: tom-home
