apiVersion: v1
kind: Secret
metadata:
    name: tom-secrets
    namespace: denny-agents
type: Opaque
stringData:
    DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:NCIbvGYZw+ODPDSbnunhkE5XUOKxj0mn0sNmEhqxc5W/x+BmOOKRqyuda5iE1CGZRu4lb3M3XFq3qFJGgk26NY+0TX52Ffgg,iv:3jbIHQfkPVHS4zGmUbMm9z8mRwS8y68aIT1a/xM+/A8=,tag:uQisj8DOQts/cuRQrfZuhQ==,type:str]
    ANTHROPIC_OAUTH_TOKEN: ENC[AES256_GCM,data:HpN0pggb1XJeFFgvPLyUHzLFLplBsubx/8v4a/R03eSLFGf/9TVpXPAqxc+EtHCn9Q3wFo+hO8FMJRJephVkTFLiudmvJAGN5Ur3WUua9lOa4e5Eugnn//mCqctcvWZ55sMmg5/cWZRLqBtw,iv:MIe2V4/LVlFeAv53HgM5rYNf54KLT6UKXcb7xOPa7kg=,tag:WM1HPclf6GX1iTSSwz/0cw==,type:str]
    GH_TOKEN: ENC[AES256_GCM,data:r2tpE5P1yZkp6afzo9XdCMkQMKbZiD4MU4YeJ/SoBSGbHBpNebhvEw==,iv:9fl7/PFFXSnMHFFUcYXLvln4HKeS7ShEd97YMe6ftIY=,tag:FX8bFxZK4PKLhEs8r55SIQ==,type:str]
    JIRA_API_TOKEN: ENC[AES256_GCM,data:h+AIK0Vh3IHPTaiewSYvGuQtvmFjz7vpYDjYSYdX/8jofxBZXzNFGGAX6F0NmXrAQSAtc4iP3md575sTml8FFgQ53YD4Pt2LobkPf4ld5l2mQBHu+LyKkGraWo5m2+vQnae7WhlpIoXFXODaFXL90NOetsCCZGGHiu1AkiNEQb8485rh+PZx8nHIVnEyPtJhoH2yf1zHI++k+vKYXneWSMjjZ+gQDhrwjRGATwWaHbsmyo/6UWo1Pr5vpYaUeSQM,iv:3NIVE4tC3hlaeAPdhNNSYmmpo4trojhtzDjQ9erjmis=,tag:yeY2kziszfMUF1YlxmMIMQ==,type:str]
sops:
    age:
        - recipient: age1xa2x5q6zpcrwjq9xyh9ghmm57mvzu5d0e0yehtqujdjfyjxpe9rqu60den
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZTVJCQUtqQXg3QmVEWVNW
            b1pDV3U4NDd3c2d6cElWWndIakpyaDhjSm0wCmpYMkhHVUVaZmRmb1hEY1JYbXlr
            YXAwN0UwWmkvK1R1NW9KU2tYQ0ZXc1EKLS0tIFhoN3NudTA4ajdHeDZjUDRHckdn
            bWVKVDAzWmc3d3kxTG50dzdCUG5GVmsKZLs+8bi3Mbg6Q+ddmyY0exmgdNvIPVXG
            4WLt76Di6UXhZIrp+AVGwD8AUTCEMLlfo5OhnoTqCcASv/c1ms7DlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-23T13:25:13Z"
    mac: ENC[AES256_GCM,data:Um26L7pMoWO3uqnR5JQoKirs6rDfHuLZ+dDoTS9EuwZlJwfIiT8dYLbOr7kS4HfS1C2W8+uCPIlGYBeTPo+LXnGD5UiZN3+8QoolO8XbDmWFSIYd9uP1r5Lx+FvwI/Zm5ZvUgEj9eSwMxqNbOPyUiGPPA/nBNpM9DzszbcctMWk=,iv:VXy159S5rD7YD6Bnv+NmpKFSzkxOdGBhwuhHfnVkeI0=,tag:xdEzsHj7NiJZ02AHh9uwvA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
